### ISSUE TITLE
[General] CMake Failed in "Debug" mode due to "test" name conflict.

### ISSUE THREAD

**Issue by trickarcher** [venkat24/tvp#27]
Steps to reproduce the issue:
Set the build to `Debug` mode and run cmake.

Possible Solution:
Change the project name to something like `tvp_test`. It seems as though there's a name conflict with CMake's own automated testing.
[Source](https://stackoverflow.com/questions/46638704/cmake-error-target-name-test-is-reserved-or-not-valid)

**Comment by venkat24** [comment]
Is this issue still present with recent CMake versions? If we can do something to avoid renaming the directory I would prefer that. `test` is quite a nice name. If not, can we name to `tests`?

**Comment by venkat24** [comment]
Closed with #28
